[package]
name = "hashibuild"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
sha2 = "0.9.5"
base64 = "0.13.0"
path-clean = "0.1.0"
serde = {  version="1.0", features=["derive"]}